/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.junit;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;


class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    class SomeClassTest {
        @Test
        public void testSum() {
            var expected = 5;
            var actual = SomeClass.sum(3, 2);
            assertEquals(expected, actual);
        }
    }
}
